-- ============================================================
-- AByte Master Database Schema
-- Phase 4+: Single-tenant conversion — master DB no longer used.
-- This file is kept for historical reference only.
-- The active schema is database/schema.sql (abyte_pos).
-- ============================================================
